### ISSUE TITLE
Fatal error in ToggleModulesCommand.php Line 62

### ISSUE THREAD

**Issue by aneek** [shelane/toggle-modules#2]
## Error Description
Fatal error: Uncaught Error: Class "Acquia\Blt\Robo\Common\UserConfig" not found in /app/vendor/shelane/toggle-modules/src/Blt/Plugin/Commands/ToggleModulesCommand.php:62

## Error Reason
After BLT 13.7.0, the `Acquia\Blt\Robo\Common\UserConfig` class is not present.

## Stack Trace
```
Fatal error: Uncaught Error: Class "Acquia\Blt\Robo\Common\UserConfig" not found in /app/vendor/shelane/toggle-modules/src/Blt/Plugin/Commands/ToggleModulesCommand.php:62
Stack trace:
#0 /app/vendor/shelane/toggle-modules/src/Blt/Plugin/Commands/ToggleModulesCommand.php(40): Acquia\ToggleModules\Blt\Plugin\Commands\ToggleModulesCommand->doToggleModules('pm-enable', 'modules.local.e...')
#1 [internal function]: Acquia\ToggleModules\Blt\Plugin\Commands\ToggleModulesCommand->toggleModules(Array)
#2 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array(Array, Array)
#3 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /app/vendor/symfony/console/Command/Command.php(312): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /app/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /app/vendor/acquia/blt/src/Robo/Application.php(31): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /app/vendor/symfony/console/Application.php(314): Acquia\Blt\Robo\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /app/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /app/vendor/consolidation/robo/src/Runner.php(282): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /app/vendor/acquia/blt/src/Robo/Blt.php(249): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Acquia\Blt\Robo\Application), Array)
#13 /app/vendor/acquia/blt/bin/blt-robo-run.php(35): Acquia\Blt\Robo\Blt->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /app/vendor/acquia/blt/bin/blt-robo.php(15): require_once('/app/vendor/acq...')
#15 /app/vendor/acquia/blt/bin/blt(11): require_once('/app/vendor/acq...')
#16 /app/vendor/bin/blt(119): include('/app/vendor/acq...')
#17 {main}
  thrown in /app/vendor/shelane/toggle-modules/src/Blt/Plugin/Commands/ToggleModulesCommand.php on line 62
```

**Comment by shelane** [comment]
Yes, I see. They dropped in in 13.7.1 with no real documentation that they did so. I'm working on an update to toggle modules. I don't think it was really ever needed, but that was Acquia wanting telemetry on everything.
